### ISSUE TITLE
Trying to set all static handlers to 'secure: always'

### ISSUE THREAD

**Issue by savraj** [jamesramsay/jekyll-app-engine#10]
So I want my site to always render as https:// url's.

this is what I have in my _config.yml right now based on the docs, and it's not quite working. The resulting `app.yaml` doesn't have `secure: always` on each static file's handler. Any help?

```yaml
app_engine:
  runtime: python37
  handlers:
    static:
      secure: always
```

**Comment by jamesramsay** [comment]
@savraj unfortunately I haven't looked at this code in years, so I can't be much help. 😢 If you work it out, do let me know!

**Comment by savraj** [comment]
haha, ok will do. Maybe I'll submit a pull request. :)

**Comment by savraj** [comment]
ok I landed on not using this plugin, and instead just using this for my app.yaml:

```yaml
  - url: /
    static_files: _site/index.html
    upload: _site/index.html
    secure: always
  - url: /(.*)
    static_files: _site/\1
    upload: _site/(.*)
    secure: always
```
