### ISSUE TITLE
Optionally strip trailing slash

### ISSUE THREAD

**Issue by jamesramsay** [jamesramsay/jekyll-app-engine#8]
Expected behaviour on jamesramsay/blog is to link to `https://blog.jramsay.com.au/archive#2016-03`, but the jekyll-app-engine output for the handler is:

``` yaml
handlers:
- url: "/archive/"
  static_files: _site/archive/index.html
  upload: _site/archive/index.html
```

Output should also support:

``` yaml
handlers:
- url: "/archive"
  static_files: _site/archive/index.html
  upload: _site/archive/index.html
```

Trailing slash is the difference between 404 and 200 response.
