### ISSUE TITLE
Travis CI - app.yaml not found

### ISSUE THREAD

**Issue by housseindjirdeh** [jamesramsay/jekyll-app-engine#9]
This is an awesome gem, thanks for building this it's been super helpful :)

When setting up a CI pipeline with Travis CI, I'm seeing the following error: `ERROR: File [app.yaml] not found.`

<img width="990" alt="screen shot 2017-05-15 at 2 16 22 pm" src="https://cloud.githubusercontent.com/assets/12476932/26072339/21b25e32-3979-11e7-8311-875adf065446.png">

I know that that `app.yaml` file gets generated within `_site` and needs to be moved up which I'm doing as part of my script step (see https://github.com/tastejs/hacker-news-pwas/blob/master/.travis.yml#L10). Is there something that I'm missing by any chance that I should be including into the build? (Or would you happen to have an example of a `.travis.yml` file where you've gotten this to work?)

**Comment by jamesramsay** [comment]
No problem @housseindjirdeh! Glad you find it useful. Here are the relevant lines from my travis config:

```yml
script:
- rake test
before_deploy:
- rake clean
- rake deploy
- mv ./_site/app.yaml ./app.yaml
deploy:
  provider: gae
  keyfile: keyfile.json
  project: swift-terminal
  skip_cleanup: true
```

I took a look at the link, but I can't see anything obviously wrong.
